### ISSUE TITLE
Larger captions should open and retract when clicked

### ISSUE THREAD

**Issue by AlbertoElias** [Financial-Times/o-gallery#26]
@triblondon "There's a feature shown on [the readme] it that we didn't implement too - captions that are too large to fit in the maximum height we allow for a caption were going to rise up to cover more of the image when clicked (and then retract when you click off them). I don't think we ever did that (or if we did, there's no demo that demonstrates it.."

**Comment by onishiweb** [comment]
Just checked and there are a) no demos that account for a very long caption, and b) the captions don't open/close when clicked. 

We could look at adding this now or in general look at the entire usability of the `o-gallery` and consider this for v2... @AlbertoElias?

**Comment by gvonkoss** [comment]
Closing in light of https://github.com/Financial-Times/o-gallery/issues/72
