### ISSUE TITLE
Drag nav not working in Safari

### ISSUE THREAD

**Issue by triblondon** [Financial-Times/o-gallery#27]
In safari, dragging the active image with the mouse picks up the image rather than navigating the slideshow, and when you release the mouse, leaves the gallery tracking your mouse pointer until you click again.

**Comment by onishiweb** [comment]
Again this is quite old, is it worth testing to see if this is still an issue?

**Comment by AlbertoElias** [comment]
This will be completely fixed with the o-gallery refactor that removes ftscroller

**Comment by onishiweb** [comment]
Will be fixed when #52 is addressed

**Comment by gvonkoss** [comment]
Closing in light of https://github.com/Financial-Times/o-gallery/issues/72
