### ISSUE TITLE
Gallery doesn't work until first `resize` event

### ISSUE THREAD

**Issue by triblondon** [Financial-Times/o-gallery#28]
http://jsbin.com/qaqokuxugumu/1/edit

My guess is that DOMContentLoaded is firing early enough that in _most_ cases, there are images that have not loaded yet.  When they do, they change the size of the page, which triggers a `window.resize` event, and we're binding to that so it triggers after the gallery has been set up.  However, if all the images have finished loading before you initialise the gallery (which we guarantee by using the `load` event in this example) then there is no resize, and the gallery doesn't work.

During init(), we should prod whatever process is triggered by the resize.

Thanks to @olizh from FT Chinese for this example.

**Comment by onishiweb** [comment]
@AlbertoElias do you think this still an issue?

**Comment by AlbertoElias** [comment]
Probably, though there is still a scroller issue. This will be completely fixed with the o-gallery refactor that removes ftscroller

**Comment by onishiweb** [comment]
Will be fixed in v2 and by addressing #52

**Comment by gvonkoss** [comment]
Closing in light of https://github.com/Financial-Times/o-gallery/issues/72
