### ISSUE TITLE
transition effect as a configuration

### ISSUE THREAD

**Issue by olizh** [Financial-Times/o-gallery#29]
I have to put this line of CSS to have a transition effect.

.ftscroller_x, .ftscroller_y{-webkit-transition: all 0.5s ease-in-out;-ms-transition: all 0.5s ease-in-out;transition: all 0.5s ease-in-out;}

However, this CSS will make the slide gesture very slow if I set "data-o-gallery-touch" to true.

Would be nice if I can set the transition effect as a configuration.

**Comment by gvonkoss** [comment]
Closing in light of https://github.com/Financial-Times/o-gallery/issues/72
