### ISSUE TITLE
Doesn't behave well when inside container with display: table

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-gallery#44]
See http://next.ft.com/7f473d26-be68-11e4-8036-00144feab7de. The gallery expands horizontally to itemWidth x numberOfItems

**Comment by kaelig** [comment]
I can't see the gallery in the link, but `display: table` is rather erratic and works differently across browsers, is there a way to wrap the gallery inside another block that's `display: block` instead?

**Comment by wheresrhys** [comment]
The display table is on body and top level div in order to give us a sticky footer. I'm trying to think of an alternative method of achieving this though.

**Comment by kaelig** [comment]
Ha ok, maybe worth experimenting with Flexbox and having a sticky footer on supporting browsers only?

**Comment by wheresrhys** [comment]
Yeah, I'm leaning towards that too now, but slightly worried about the flex
box performance issues you sometimes read about

On Thursday, April 9, 2015, Kaelig <notifications@github.com> wrote:

> Ha ok, maybe worth experimenting with Flexbox and having a sticky footer
> on supporting browsers only?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/o-gallery/issues/44#issuecomment-91295678>
> .
>

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by kaelig** [comment]
Actually Google now recommends flexbox (new syntax only) for more
performant layouts.

On Thursday, 9 April 2015, Rhys Evans <notifications@github.com> wrote:

> Yeah, I'm leaning towards that too now, but slightly worried about the flex
> box performance issues you sometimes read about
>
> On Thursday, April 9, 2015, Kaelig <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Ha ok, maybe worth experimenting with Flexbox and having a sticky footer
> > on supporting browsers only?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/Financial-Times/o-gallery/issues/44#issuecomment-91295678
> >
> > .
> >
>
> --
>
> ------------------------------
> This email was sent by a company owned by Pearson plc, registered office
> at
> 80 Strand, London WC2R 0RL. Registered in England and Wales with company
> number 53723.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/o-gallery/issues/44#issuecomment-91314699>
> .
>

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by onishiweb** [comment]
Is this still an issue worth looking into?

**Comment by wheresrhys** [comment]
Maybe worth adding a note to the README, but otherwise not  an important issue. Just noticed there's no issue for it, but my #1 feature request for o0gallery is to remove the ftscroller dependency - it's huge, and slow to build

**Comment by onishiweb** [comment]
Ok I'll add a note to the readme about it then and change this to a docs issue. 

Feel free to add an issue for the ftscroller dep, I think there's some bigger work on rewriting this entirely soon, so it's possible it will be addressed!
