### ISSUE TITLE
Add option for full screen viewing

### ISSUE THREAD

**Issue by richard-still-ft** [Financial-Times/o-gallery#48]
Would be nice.

**Comment by richard-still-ft** [comment]
Viewing Next the lack of full screen viewing popped up again. If we have gone to effort of publishing a slideshow it had to be worth letting the user get the most from the images: http://www.theguardian.com/world/gallery/2016/feb/05/the-psychedelic-world-of-sudans-sufis-in-pictures#img-4

A good example https://next.ft.com/content/d7dea2b4-cb3a-11e5-be0b-b7ece4e953a0

**Comment by alicebartlett** [comment]
I agree that this would be a good feature, the component was originally built with to support this functionality but it was never added.

We have a new developer starting in two weeks who could probably look at this once he gets settled in, alternatively we'd welcome a PR from Next to add this feature.

**Comment by gvonkoss** [comment]
Closing in light of https://github.com/Financial-Times/o-gallery/issues/72
